fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: editorconfig-checker
        name: editorconfig-checker
        entry: ec src/
        language: python
        pass_filenames: no
        additional_dependencies: [editorconfig-checker]

      - id: linters-ruff
        name: ruff
        entry: ruff check ./src
        language: python
        pass_filenames: no
        additional_dependencies: [ruff]
